### ISSUE TITLE
sh ./uploadCloudFunction.sh 运行报错

### ISSUE THREAD

**Issue by lizhuoyuan** [LCM9902/Duck-Princess-Cultivation-Plan#1]
![image](https://user-images.githubusercontent.com/15923901/160767812-f04df597-04a5-4beb-b0fa-519236ba53e9.png)

**Comment by ZJUZZ** [comment]
你竟然尝试了。我女朋友也从小红书转发给我看了哈哈

**Comment by LCM9902** [comment]
看看你工程名和配置文件中是否匹配呢

**Comment by lizhuoyuan** [comment]
@LCM9902  我是直接下载下来什么也没改
  "projectname": "Duck-Princess-Cultivation-Plan-master"
和下载下来的文件夹一致

**Comment by lizhuoyuan** [comment]
> 你竟然尝试了。我女朋友也从小红书转发给我看了哈哈

但是我还没有跑起来
我是个不会小程序开发的程序员 QAQ

**Comment by jozhn** [comment]
有两个问题，一个是envList.js里面他填的是他的环境id，第二个是没有云数据库的结构，所以没法直接用的

**Comment by lizhuoyuan** [comment]
> 有两个问题，一个是envList.js里面他填的是他的环境id，第二个是没有云数据库的结构，所以没法直接用的

感谢， 那我没了。
我不会小程序开发 _(:з」∠)_

**Comment by LCM9902** [comment]
readme贴了下数据库设计

**Comment by lizhuoyuan** [comment]
> readme贴了下数据库设计

牛蛙，我看看我能不能0基础拿下

**Comment by lly1** [comment]
老哥，飞书文档没权限

**Comment by vvwBai** [comment]
老哥，求开放飞书文档

**Comment by 4542elgh** [comment]
总体结构不算复杂 没有碰过微信小程序的程序员 我一个小时让这个东西跑起来了。过两天把这个项目的README 和 bat文件更新一下 看看作者能不能采纳。

**Comment by LCM9902** [comment]
> 总体结构不算复杂 没有碰过微信小程序的程序员 我一个小时让这个东西跑起来了。过两天把这个项目的README 和 bat文件更新一下 看看作者能不能采纳。

牛逼 欢迎补充

**Comment by LCM9902** [comment]
> 总体结构不算复杂 没有碰过微信小程序的程序员 我一个小时让这个东西跑起来了。过两天把这个项目的README 和 bat文件更新一下 看看作者能不能采纳。

可以补充下用的过程中有哪些坑

**Comment by vvwBai** [comment]
> > 总体结构不算复杂 没有碰过微信小程序的程序员 我一个小时让这个东西跑起来了。过两天把这个项目的README 和 bat文件更新一下 看看作者能不能采纳。
> 
> 可以补充下用的过程中有哪些坑

还有就是envList.js 文件中，要记得把envId 换成自己的环境 ， 刚刚试了一下有部分方法跑不起来，看了下环境id跟我的不一样
