### ISSUE TITLE
修改user表中名字和js中的名字后获取不到用户信息

### ISSUE THREAD

**Issue by zhangruiwei** [LCM9902/Duck-Princess-Cultivation-Plan#11]
rt，修改后查看日志获取的用户为空，改回"高高"又可以获取成功了

**Comment by Lxy12138** [comment]
把代码里全部的“高高”替换掉，并且在数据库里建立user表，添加同名数据

**Comment by zhangruiwei** [comment]
> 把代码里全部的“高高”替换掉，并且在数据库里建立user表，添加同名数据

标题有写了，替换了js里面的3处"高高"，并且改成“ABC”，同时user表的名字也改成"ABC"，但是查询出来是空的，同样的把js和user表改回去就没问题可以显示。。。 奇怪了，不知道你们是怎么正常改名并且显示使用的 。

**Comment by zhangruiwei** [comment]
没问题了  数据集合重建搞定了

**Comment by MikeChen0337** [comment]
你好请问数据集合重建具体操作怎么搞哇 我比较小白呜呜呜
