### ISSUE TITLE
用户表创建了，为什么点击兑换查询不到user_integral呀

### ISSUE THREAD

**Issue by Moonquakesss** [LCM9902/Duck-Princess-Cultivation-Plan#2]
<img width="815" alt="image" src="https://user-images.githubusercontent.com/30189760/160814464-3cbba516-0b6a-41ce-9ecc-142edc9f2255.png">
<img width="786" alt="image" src="https://user-images.githubusercontent.com/30189760/160814524-351451aa-830d-4823-8d72-2b6956eea007.png">

**Comment by SoberY** [comment]
文件搜索下 user_name这个关键字, 作者估计是写着玩的 写死了这个value, 一个个改过去就好了

**Comment by LCM9902** [comment]
对 这里贪省事 直接写死了

**Comment by HuangYH1996** [comment]
> 

是的，我把写死的value改成我 user表里面的 user_name了，但是还是报这个错。

**Comment by Moonquakesss** [comment]
> 文件搜索下 user_name这个关键字, 作者估计是写着玩的 写死了这个value, 一个个改过去就好了
是的，我把写死的value改成我 user表里面的 user_name了，还是报这个错。

**Comment by zmlinn** [comment]
> > 文件搜索下 user_name这个关键字, 作者估计是写着玩的 写死了这个value, 一个个改过去就好了
> > 是的，我把写死的value改成我 user表里面的 user_name了，还是报这个错。

我把云函数里面的selectUser重新部署之后，解决了

**Comment by Moonquakesss** [comment]
> 文件搜索下 user_name这个关键字, 作者估计是写着玩的 写死了这个value, 一个个改过去就好了



> 

感谢～
