### ISSUE TITLE
执行uploadCloudFunction.sh后显示报错

### ISSUE THREAD

**Issue by Ricardowdl** [LCM9902/Duck-Princess-Cultivation-Plan#5]
如图
macOs  appId（为正式appId，非游客）与projectname已修改为自己的
![image](https://user-images.githubusercontent.com/57186816/160977510-5ca961cf-a0ba-4b90-a18c-73d49ebad4b6.png)

**Comment by 4542elgh** [comment]
请检查 uploadCloudFunction.sh 里的命令是否正确, CloudID 和 最后的工程文件目录要对应你的文件夹。 我会在后续添加一个 相对路径的 .sh 脚本 就不会有这种情况了

**Comment by Ricardowdl** [comment]
> 请检查 uploadCloudFunction.sh 里的命令是否正确, CloudID 和 最后的工程文件目录要对应你的文件夹。 我会在后续添加一个 相对路径的 .sh 脚本 就不会有这种情况了

了解，更换uploadCloudFunction.sh 内的命令后已解决
