### ISSUE TITLE
完成任务里面点击，出现错误

### ISSUE THREAD

**Issue by 123leechm** [LCM9902/Duck-Princess-Cultivation-Plan#7]
错误如下：
Error: errCode: -404011 cloud function execution error | errMsg: cloud.callFunction:fail requestID 63bf817b-5121-4855-b563-daea35361e5e, cloud function service error code -504002, error message TypeError: Cannot read property 'user_integral' of undefined

user_integral这个未定义，是云函数的问题嘛？

**Comment by 123leechm** [comment]
已解决。。。。

**Comment by fuujiro** [comment]
怎么解决的 求教 好兄弟

**Comment by WangYP997** [comment]
求
